taking different approach without artifacts

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -21,6 +21,8 @@ jobs:
         uses: actions/checkout@v3
         with:
           path: .ansible/collections/ansible_collections/linode/cloud
+          fetch-depth: 0
+          submodules: 'recursive'
 
       - name: update packages
         run: sudo apt-get update -y
@@ -51,59 +53,17 @@ jobs:
             echo "EXIT_STATUS=1" >> $GITHUB_ENV
           fi
           cat test_output.txt
-          pwd
-          ls -a tests/output/junit/
-          cat tests/output/junit/*.xml
         env:
           LINODE_API_TOKEN: ${{ secrets.DX_LINODE_TOKEN }}
           ANSIBLE_CALLBACKS_ENABLED: "junit"
-
-      - name: Upload test report as artifact
-        id: upload-artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-report-dir
-          path: tests/output/
-
-      - name: Test Execution Status Handler
-        run: |
-          if [[ "$EXIT_STATUS" != 0 ]]; then
-            echo "Test execution contains failure(s), check Run Integration tests step above"
-            exit $EXIT_STATUS 
-          else
-            echo "Tests passed!"
-          fi
-
-  process-upload-report:
-    runs-on: ubuntu-latest
-    needs:
-      - run-tests
-    if: ${{ needs.run-tests.outputs.upload-artifact == 'success' }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          submodules: 'recursive'
-
-      - name: Download test report
-        uses: actions/download-artifact@v4
-        with:
-          name: test-report-dir
-
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.x'
-
-      - name: Install Python dependencies
-        run: pip3 install requests wheel boto3
 
       - name: Set release version env
         run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
 
       - name: Merge all test xmls in output directory
         run: |
+          pwd
+          ls
           python tod_scripts/merge_ansible_results.py
 
       - name: Add additional information to XML report
@@ -122,3 +82,13 @@ jobs:
         env:
           LINODE_CLI_OBJ_ACCESS_KEY: ${{ secrets.LINODE_CLI_OBJ_ACCESS_KEY }}
           LINODE_CLI_OBJ_SECRET_KEY: ${{ secrets.LINODE_CLI_OBJ_SECRET_KEY }}
+
+      - name: Test Execution Status Handler
+        run: |
+          if [[ "$EXIT_STATUS" != 0 ]]; then
+            echo "Test execution contains failure(s), check Run Integration tests step above"
+            exit $EXIT_STATUS 
+          else
+            echo "Tests passed!"
+          fi
+
